services:
  api:
    container_name: cb-digital-interview-be
    image: cb-digital-interview-be
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - database

  api-dev:
    container_name: cb-digital-interview-be-dev
    image: cb-digital-interview-be-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - database

  database:
    image: mongo:7
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    volumes:
      - cb-digital-db:/data/db

volumes:
  cb-digital-db:
